### ISSUE TITLE
Wrong sizes

### ISSUE THREAD

**Issue by weranda** [nkanaev/imgspy#1]
I'm  trying to get the image size (width, height) with imgspy.
Image URL: https://i.ibb.co/DwktdyX/111.jpg
Why imgspy returns wrong sizes?

True/Valid width and height — 600/450 px.
imgspy returns — 160/120 px.

Why?

P.S.
Additional image URL for testing: https://upload.wikimedia.org/wikipedia/commons/d/d2/2018_Audi_A7_S_Line_40_TDi_S-A_2.0.jpg

**Comment by nkanaev** [comment]
thanks for reporting.

i've fixed the issue in  https://github.com/nkanaev/imgspy/commit/7272be723c5bbb2b912e5bcba54fd39ebb06ab2d.
